import type { LucideIcon } from "lucide-react";
import {
	Archive,
	BarChart3,
	Blocks,
	Box,
	Cpu,
	Database,
	Gauge,
	Globe,
	Hexagon,
	Image,
	Layers,
	MessageSquare,
	Network,
	Plug,
	SearchCode,
	Settings as SettingsIcon,
	Shield,
	SlidersHorizontal,
	Smartphone,
	Sparkles,
	Terminal,
	Wind,
	Workflow,
} from "lucide-react";
import { ProviderType } from "../../types";

export const SETTINGS_MENU = [
	{ id: "dashboard", label: "使用统计", icon: BarChart3 },
	{ id: "models", label: "模型配置", icon: Cpu },
	{ id: "prompts", label: "提示词配置", icon: MessageSquare },
	{ id: "imagegen", label: "AI 生图", icon: Image },
	{ id: "mascot", label: "IP 形象", icon: Sparkles },
	{ id: "agent", label: "Agent 设置", icon: Shield },
	{ id: "skills", label: "Agent 技能", icon: Blocks },
	{ id: "mcp", label: "MCP 配置", icon: Plug },
	{ id: "remoteControl", label: "远程控制", icon: Smartphone },
	{ id: "general", label: "常规设置", icon: SettingsIcon },
	{ id: "performance", label: "性能优化", icon: Gauge },
	{ id: "data", label: "数据与同步", icon: Database },
	{ id: "artifacts", label: "产物管理", icon: Archive },
];

export interface ProviderTemplate {
	templateId: string;
	name: string;
	providerType: ProviderType;
	icon: LucideIcon;
	color: string;
	defaultEnabled: boolean;
	defaultApiBase?: string;
	defaultModels: string[];
	homeUrl?: string; // 官网首页
	apiKeyUrl?: string; // API Key 获取链接
	docsUrl?: string; // 官方文档
	modelsUrl?: string; // 模型列表/模型文档
}

export const PROVIDER_TEMPLATES: ProviderTemplate[] = [
	// 主流 AI 厂商
	{
		templateId: "openai",
		name: "OpenAI",
		providerType: ProviderType.OpenAi,
		icon: Box,
		color: "bg-[#10A37F]",
		defaultEnabled: true,
		defaultApiBase: "https://api.openai.com",
		defaultModels: ["gpt-5", "gpt-5-mini", "gpt-4.1", "o3-mini", "gpt-4o"],
		homeUrl: "https://openai.com/",
		apiKeyUrl: "https://platform.openai.com/api-keys",
		docsUrl: "https://platform.openai.com/docs",
		modelsUrl: "https://platform.openai.com/docs/models",
	},
	{
		templateId: "anthropic",
		name: "Claude",
		providerType: ProviderType.Anthropic,
		icon: Hexagon,
		color: "bg-[#D97757]",
		defaultEnabled: false,
		defaultApiBase: "https://api.anthropic.com",
		defaultModels: [
			"claude-sonnet-4-5",
			"claude-opus-4-5",
			"claude-3.7-sonnet",
			"claude-3.5-sonnet",
			"claude-3-haiku",
		],
		homeUrl: "https://anthropic.com/",
		apiKeyUrl: "https://console.anthropic.com/settings/keys",
		docsUrl: "https://docs.anthropic.com/en/docs",
		modelsUrl: "https://docs.anthropic.com/en/docs/about-claude/models",
	},
	{
		templateId: "gemini",
		name: "Google Gemini",
		providerType: ProviderType.Custom,
		icon: Globe,
		color: "bg-[#4285F4]",
		defaultEnabled: false,
		defaultApiBase: "https://generativelanguage.googleapis.com",
		defaultModels: [
			"gemini-2.5-flash",
			"gemini-2.0-flash-exp",
			"gemini-1.5-pro",
			"gemini-1.5-flash",
		],
		homeUrl: "https://gemini.google.com/",
		apiKeyUrl: "https://aistudio.google.com/app/apikey",
		docsUrl: "https://ai.google.dev/gemini-api/docs",
		modelsUrl: "https://ai.google.dev/gemini-api/docs/models/gemini",
	},
	{
		templateId: "deepseek",
		name: "DeepSeek",
		providerType: ProviderType.Deepseek,
		icon: SearchCode,
		color: "bg-[#4D6BFE]",
		defaultEnabled: false,
		defaultApiBase: "https://api.deepseek.com",
		defaultModels: ["deepseek-chat", "deepseek-reasoner", "deepseek-r1"],
		homeUrl: "https://deepseek.com/",
		apiKeyUrl: "https://platform.deepseek.com/api_keys",
		docsUrl: "https://platform.deepseek.com/api-docs/",
		modelsUrl: "https://platform.deepseek.com/api-docs/",
	},
	{
		templateId: "groq",
		name: "Groq",
		providerType: ProviderType.Custom,
		icon: Gauge,
		color: "bg-[#F55036]",
		defaultEnabled: false,
		defaultApiBase: "https://api.groq.com/openai",
		defaultModels: ["llama-3.3-70b-versatile", "mixtral-8x7b-32768"],
		homeUrl: "https://groq.com/",
		apiKeyUrl: "https://console.groq.com/keys",
		docsUrl: "https://console.groq.com/docs/quickstart",
		modelsUrl: "https://console.groq.com/docs/models",
	},
	{
		templateId: "mistral",
		name: "Mistral AI",
		providerType: ProviderType.Custom,
		icon: Wind,
		color: "bg-[#FF4F00]",
		defaultEnabled: false,
		defaultApiBase: "https://api.mistral.ai",
		defaultModels: ["mistral-large-latest", "mistral-medium-latest"],
		homeUrl: "https://mistral.ai",
		apiKeyUrl: "https://console.mistral.ai/api-keys/",
		docsUrl: "https://docs.mistral.ai",
		modelsUrl: "https://docs.mistral.ai/getting-started/models/models_overview",
	},
	{
		templateId: "together",
		name: "Together AI",
		providerType: ProviderType.Custom,
		icon: Box,
		color: "bg-[#6366F1]",
		defaultEnabled: false,
		defaultApiBase: "https://api.together.xyz",
		defaultModels: ["meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo"],
		homeUrl: "https://www.together.ai/",
		apiKeyUrl: "https://api.together.ai/settings/api-keys",
		docsUrl: "https://docs.together.ai/docs/introduction",
		modelsUrl: "https://docs.together.ai/docs/chat-models",
	},
	{
		templateId: "openrouter",
		name: "OpenRouter",
		providerType: ProviderType.Custom,
		icon: Network,
		color: "bg-[#9333EA]",
		defaultEnabled: false,
		defaultApiBase: "https://openrouter.ai/api/v1/",
		defaultModels: [],
		homeUrl: "https://openrouter.ai/",
		apiKeyUrl: "https://openrouter.ai/settings/keys",
		docsUrl: "https://openrouter.ai/docs/quick-start",
		modelsUrl: "https://openrouter.ai/models",
	},
	{
		templateId: "fireworks",
		name: "Fireworks AI",
		providerType: ProviderType.Custom,
		icon: Box,
		color: "bg-[#FF6B6B]",
		defaultEnabled: false,
		defaultApiBase: "https://api.fireworks.ai/inference",
		defaultModels: ["accounts/fireworks/models/llama-v3p3-70b-instruct"],
		homeUrl: "https://fireworks.ai/",
		apiKeyUrl: "https://fireworks.ai/account/api-keys",
		docsUrl: "https://docs.fireworks.ai/getting-started/introduction",
		modelsUrl: "https://fireworks.ai/dashboard/models",
	},
	{
		templateId: "perplexity",
		name: "Perplexity",
		providerType: ProviderType.Custom,
		icon: Box,
		color: "bg-[#20808D]",
		defaultEnabled: false,
		defaultApiBase: "https://api.perplexity.ai/",
		defaultModels: ["llama-3.1-sonar-large-128k-online"],
		homeUrl: "https://perplexity.ai/",
		apiKeyUrl: "https://www.perplexity.ai/settings/api",
		docsUrl: "https://docs.perplexity.ai/home",
		modelsUrl: "https://docs.perplexity.ai/guides/model-cards",
	},
	{
		templateId: "cerebras",
		name: "Cerebras AI",
		providerType: ProviderType.Custom,
		icon: Box,
		color: "bg-[#00C4B3]",
		defaultEnabled: false,
		defaultApiBase: "https://api.cerebras.ai/v1",
		defaultModels: ["llama3.1-70b"],
		homeUrl: "https://www.cerebras.ai",
		apiKeyUrl: "https://cloud.cerebras.ai",
		docsUrl: "https://inference-docs.cerebras.ai/introduction",
		modelsUrl: "https://inference-docs.cerebras.ai/models/overview",
	},
	{
		templateId: "hyperbolic",
		name: "Hyperbolic",
		providerType: ProviderType.Custom,
		icon: Box,
		color: "bg-[#7C3AED]",
		defaultEnabled: false,
		defaultApiBase: "https://api.hyperbolic.xyz",
		defaultModels: ["meta-llama/Meta-Llama-3.1-70B-Instruct"],
		homeUrl: "https://app.hyperbolic.xyz",
		apiKeyUrl: "https://app.hyperbolic.xyz/settings",
		docsUrl: "https://docs.hyperbolic.xyz",
		modelsUrl: "https://app.hyperbolic.xyz/models",
	},
	// 本地部署
	{
		templateId: "ollama",
		name: "Ollama",
		providerType: ProviderType.Ollama,
		icon: Terminal,
		color: "bg-zinc-800",
		defaultEnabled: false,
		defaultApiBase: "http://localhost:11434",
		defaultModels: ["llama3.3", "qwen2.5", "deepseek-r1"],
		docsUrl: "https://ollama.com/library",
		homeUrl: "https://ollama.com/",
		modelsUrl: "https://ollama.com/library",
	},
	{
		templateId: "lmstudio",
		name: "LM Studio",
		providerType: ProviderType.Custom,
		icon: Terminal,
		color: "bg-zinc-700",
		defaultEnabled: false,
		defaultApiBase: "http://localhost:1234",
		defaultModels: [],
		docsUrl: "https://lmstudio.ai/docs",
		homeUrl: "https://lmstudio.ai/",
		modelsUrl: "https://lmstudio.ai/models",
	},
	{
		templateId: "newapi",
		name: "New API",
		providerType: ProviderType.Custom,
		icon: Terminal,
		color: "bg-blue-600",
		defaultEnabled: false,
		defaultApiBase: "http://localhost:3000",
		defaultModels: [],
		docsUrl: "https://github.com/Calcium-Ion/new-api",
		homeUrl: "https://github.com/Calcium-Ion/new-api",
	},
	{
		templateId: "github",
		name: "GitHub Models",
		providerType: ProviderType.Custom,
		icon: Box,
		color: "bg-[#24292F]",
		defaultEnabled: false,
		defaultApiBase: "https://models.github.ai/inference",
		defaultModels: ["gpt-4o", "gpt-4o-mini"],
		homeUrl: "https://github.com/marketplace/models",
		apiKeyUrl: "https://github.com/settings/tokens",
		docsUrl:
			"https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token",
		modelsUrl: "https://github.com/marketplace/models",
	},
	// 国内代理/聚合
	{
		templateId: "silicon",
		name: "Silicon Flow",
		providerType: ProviderType.Custom,
		icon: Box,
		color: "bg-[#5B6EF8]",
		defaultEnabled: false,
		defaultApiBase: "https://api.siliconflow.cn",
		defaultModels: ["Qwen/Qwen2.5-72B-Instruct", "deepseek-ai/DeepSeek-V3"],
		homeUrl: "https://www.siliconflow.cn",
		apiKeyUrl: "https://cloud.siliconflow.cn/i/d1nTBKXU",
		docsUrl: "https://docs.siliconflow.cn/",
		modelsUrl: "https://cloud.siliconflow.cn/models",
	},
	{
		templateId: "aihubmix",
		name: "AiHubMix",
		providerType: ProviderType.Custom,
		icon: Box,
		color: "bg-[#10B981]",
		defaultEnabled: false,
		defaultApiBase: "https://aihubmix.com",
		defaultModels: [],
		apiKeyUrl: "https://aihubmix.com",
		docsUrl: "https://doc.aihubmix.com/",
		homeUrl: "https://aihubmix.com",
		modelsUrl: "https://aihubmix.com/models",
	},
	{
		templateId: "zhipu",
		name: "智谱 AI",
		providerType: ProviderType.Custom,
		icon: Layers,
		color: "bg-[#3B5998]",
		defaultEnabled: false,
		defaultApiBase: "https://open.bigmodel.cn/api/paas/v4/",
		defaultModels: ["glm-4-plus", "glm-4-0520", "glm-4-flash", "glm-4-air"],
		homeUrl: "https://open.bigmodel.cn/",
		apiKeyUrl: "https://open.bigmodel.cn/usercenter/apikeys",
		docsUrl: "https://docs.bigmodel.cn/",
		modelsUrl: "https://open.bigmodel.cn/modelcenter/square",
	},
	{
		templateId: "moonshot",
		name: "Moonshot (Kimi)",
		providerType: ProviderType.Custom,
		icon: Globe,
		color: "bg-[#000000]",
		defaultEnabled: false,
		defaultApiBase: "https://api.moonshot.cn",
		defaultModels: ["moonshot-v1-8k", "moonshot-v1-32k", "moonshot-v1-128k"],
		homeUrl: "https://www.moonshot.cn/",
		apiKeyUrl: "https://platform.moonshot.cn/console/api-keys",
		docsUrl: "https://platform.moonshot.cn/docs/",
		modelsUrl:
			"https://platform.moonshot.cn/docs/intro#%E6%A8%A1%E5%9E%8B%E5%88%97%E8%A1%A8",
	},
	{
		templateId: "cherryin",
		name: "CherryIN",
		providerType: ProviderType.Custom,
		icon: Network,
		color: "bg-[#E11D48]",
		defaultEnabled: false,
		defaultApiBase: "https://open.cherryin.cc",
		defaultModels: [],
		homeUrl: "https://open.cherryin.ai",
		apiKeyUrl: "https://open.cherryin.ai/console/token",
		docsUrl: "https://open.cherryin.ai",
		modelsUrl: "https://open.cherryin.ai/pricing",
	},
	{
		templateId: "ovms",
		name: "OpenVINO Model Server",
		providerType: ProviderType.Custom,
		icon: Box,
		color: "bg-[#2563EB]",
		defaultEnabled: false,
		defaultApiBase: "http://localhost:8000/v3/",
		defaultModels: [],
		homeUrl:
			"https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/overview.html",
		docsUrl:
			"https://docs.openvino.ai/2025/model-server/ovms_what_is_openvino_model_server.html",
		modelsUrl: "https://www.modelscope.cn/organization/OpenVINO",
	},
	{
		templateId: "ocoolai",
		name: "ocoolAI",
		providerType: ProviderType.Custom,
		icon: Box,
		color: "bg-[#0F766E]",
		defaultEnabled: false,
		defaultApiBase: "https://api.ocoolai.com",
		defaultModels: [
			"deepseek-chat",
			"deepseek-reasoner",
			"gpt-4o",
			"claude-3-5-sonnet-20240620",
		],
		homeUrl: "https://one.ocoolai.com/",
		apiKeyUrl: "https://one.ocoolai.com/token",
		docsUrl: "https://docs.ocoolai.com/",
		modelsUrl: "https://api.ocoolai.com/info/models/",
	},
	{
		templateId: "alayanew",
		name: "AlayaNew",
		providerType: ProviderType.Custom,
		icon: Globe,
		color: "bg-[#8B5CF6]",
		defaultEnabled: false,
		defaultApiBase: "https://deepseek.alayanew.com",
		defaultModels: [],
		homeUrl: "https://www.alayanew.com/backend/register?id=cherrystudio",
		apiKeyUrl: "https://www.alayanew.com/backend/register?id=cherrystudio",
		docsUrl:
			"https://docs.alayanew.com/docs/modelService/interview?utm_source=cherrystudio",
		modelsUrl: "https://www.alayanew.com/product/deepseek?id=cherrystudio",
	},
	{
		templateId: "aionly",
		name: "AIOnly",
		providerType: ProviderType.Custom,
		icon: Box,
		color: "bg-[#111827]",
		defaultEnabled: false,
		defaultApiBase: "https://api.aiionly.com",
		defaultModels: [
			"claude-sonnet-4-6",
			"gpt-5.4",
			"gemini-3.1-pro-preview",
			"gemini-2.5-flash",
		],
		homeUrl: "https://www.aiionly.com",
		apiKeyUrl: "https://maas.aiionly.com/keyApi",
		docsUrl: "https://maas.aiionly.com/document",
		modelsUrl: "https://maas.aiionly.com",
	},
	{
		templateId: "burncloud",
		name: "BurnCloud",
		providerType: ProviderType.Custom,
		icon: Box,
		color: "bg-[#F97316]",
		defaultEnabled: false,
		defaultApiBase: "https://ai.burncloud.com",
		defaultModels: [
			"claude-sonnet-4-5-20250929",
			"gpt-5",
			"gemini-2.5-pro",
			"deepseek-chat",
		],
		homeUrl: "https://ai.burncloud.com/",
		apiKeyUrl: "https://ai.burncloud.com/token",
		docsUrl: "https://ai.burncloud.com/docs",
		modelsUrl: "https://ai.burncloud.com/pricing",
	},
	{
		templateId: "cephalon",
		name: "Cephalon",
		providerType: ProviderType.Custom,
		icon: Box,
		color: "bg-[#0F172A]",
		defaultEnabled: false,
		defaultApiBase: "https://cephalon.cloud/user-center/v1/model",
		defaultModels: ["DeepSeek-R1"],
		homeUrl: "https://cephalon.cloud/share/register-landing?invite_id=jSdOYA",
		apiKeyUrl: "https://cephalon.cloud/api",
		docsUrl: "https://cephalon.cloud/apitoken/1864244127731589124",
		modelsUrl: "https://cephalon.cloud/model",
	},
	{
		templateId: "lanyun",
		name: "Lanyun",
		providerType: ProviderType.Custom,
		icon: Network,
		color: "bg-[#0284C7]",
		defaultEnabled: false,
		defaultApiBase: "https://maas-api.lanyun.net",
		defaultModels: [
			"/maas/deepseek-ai/DeepSeek-R1-0528",
			"/maas/deepseek-ai/DeepSeek-V3-0324",
			"/maas/qwen/Qwen2.5-72B-Instruct",
		],
		homeUrl: "https://maas.lanyun.net",
		apiKeyUrl: "https://maas.lanyun.net/#/system/apiKey",
		docsUrl: "https://archive.lanyun.net/#/maas/",
		modelsUrl: "https://maas.lanyun.net/#/model/modelSquare",
	},
	{
		templateId: "ph8",
		name: "PH8",
		providerType: ProviderType.Custom,
		icon: Gauge,
		color: "bg-[#EA580C]",
		defaultEnabled: false,
		defaultApiBase: "https://ph8.co",
		defaultModels: ["deepseek-v3-241226", "deepseek-r1-250120"],
		homeUrl: "https://ph8.co",
		apiKeyUrl: "https://ph8.co/apiKey",
		docsUrl: "https://m1r239or5aw.feishu.cn/wiki/SegzwS4x1i2P4OksFY2cMvujn9f",
		modelsUrl: "https://ph8.co/v1/models",
	},
	{
		templateId: "sophnet",
		name: "SophNet",
		providerType: ProviderType.Custom,
		icon: Network,
		color: "bg-[#1D4ED8]",
		defaultEnabled: false,
		defaultApiBase: "https://www.sophnet.com/api/open-apis/v1",
		defaultModels: [],
		homeUrl: "https://sophnet.com",
		apiKeyUrl: "https://sophnet.com/#/project/key",
		docsUrl: "https://sophnet.com/docs/component/introduce.html",
		modelsUrl: "https://sophnet.com/#/model/list",
	},
	{
		templateId: "dashscope",
		name: "阿里百炼",
		providerType: ProviderType.Custom,
		icon: Layers,
		color: "bg-[#FF6A00]",
		defaultEnabled: false,
		defaultApiBase: "https://dashscope.aliyuncs.com/compatible-mode/v1/",
		defaultModels: ["qwen3.5-plus", "qwen3.5-flash", "qwen3-max"],
		homeUrl: "https://www.aliyun.com/product/bailian",
		apiKeyUrl: "https://bailian.console.aliyun.com/?tab=model#/api-key",
		docsUrl: "https://help.aliyun.com/zh/model-studio/getting-started/",
		modelsUrl: "https://bailian.console.aliyun.com/?tab=model#/model-market",
	},
	{
		templateId: "modelscope",
		name: "ModelScope",
		providerType: ProviderType.Custom,
		icon: Network,
		color: "bg-[#624AFF]",
		defaultEnabled: false,
		defaultApiBase: "https://api-inference.modelscope.cn/v1/",
		defaultModels: [
			"Qwen/Qwen2.5-72B-Instruct",
			"Qwen/Qwen2.5-Coder-32B-Instruct",
			"deepseek-ai/DeepSeek-R1",
			"deepseek-ai/DeepSeek-V3",
		],
		homeUrl: "https://modelscope.cn",
		apiKeyUrl: "https://modelscope.cn/my/myaccesstoken",
		docsUrl: "https://modelscope.cn/docs/model-service/API-Inference/intro",
		modelsUrl: "https://modelscope.cn/models",
	},
	{
		templateId: "doubao",
		name: "火山方舟",
		providerType: ProviderType.Custom,
		icon: Box,
		color: "bg-[#1D4ED8]",
		defaultEnabled: false,
		defaultApiBase: "https://ark.cn-beijing.volces.com/api/v3/",
		defaultModels: [
			"doubao-seed-1-8-251228",
			"doubao-1-5-vision-pro-32k-250115",
			"doubao-1-5-pro-32k-250115",
			"doubao-1-5-pro-256k-250115",
		],
		homeUrl: "https://console.volcengine.com/ark/",
		apiKeyUrl:
			"https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey",
		docsUrl: "https://www.volcengine.com/docs/82379/1182403",
		modelsUrl:
			"https://console.volcengine.com/ark/region:ark+cn-beijing/endpoint",
	},
	{
		templateId: "minimax",
		name: "MiniMax",
		providerType: ProviderType.Custom,
		icon: MessageSquare,
		color: "bg-[#111827]",
		defaultEnabled: false,
		defaultApiBase: "https://api.minimaxi.com/v1/",
		defaultModels: [
			"MiniMax-M2.7",
			"MiniMax-M2.7-highspeed",
			"MiniMax-M2.5",
			"MiniMax-M2",
		],
		homeUrl: "https://platform.minimaxi.com/",
		apiKeyUrl:
			"https://platform.minimaxi.com/user-center/basic-information/interface-key",
		docsUrl: "https://platform.minimaxi.com/docs/api-reference/text-openai-api",
		modelsUrl: "https://platform.minimaxi.com/document/Models",
	},
	{
		templateId: "minimax-global",
		name: "MiniMax Global",
		providerType: ProviderType.Custom,
		icon: MessageSquare,
		color: "bg-[#1F2937]",
		defaultEnabled: false,
		defaultApiBase: "https://api.minimax.io/v1/",
		defaultModels: ["MiniMax-M2.7", "MiniMax-M2.5", "MiniMax-M2"],
		homeUrl: "https://platform.minimax.io/",
		apiKeyUrl:
			"https://platform.minimax.io/user-center/basic-information/interface-key",
		docsUrl: "https://platform.minimax.io/docs/api-reference/text-openai-api",
		modelsUrl: "https://platform.minimax.io/document/Models",
	},
	{
		templateId: "baichuan",
		name: "百川智能",
		providerType: ProviderType.Custom,
		icon: Layers,
		color: "bg-[#2563EB]",
		defaultEnabled: false,
		defaultApiBase: "https://api.baichuan-ai.com",
		defaultModels: [
			"Baichuan4",
			"Baichuan4-Turbo",
			"Baichuan4-Air",
			"Baichuan-M2-Plus",
		],
		homeUrl: "https://www.baichuan-ai.com/",
		apiKeyUrl: "https://platform.baichuan-ai.com/console/apikey",
		docsUrl: "https://platform.baichuan-ai.com/docs",
		modelsUrl: "https://platform.baichuan-ai.com/prices",
	},
	{
		templateId: "stepfun",
		name: "阶跃星辰",
		providerType: ProviderType.Custom,
		icon: SlidersHorizontal,
		color: "bg-[#7C3AED]",
		defaultEnabled: false,
		defaultApiBase: "https://api.stepfun.com",
		defaultModels: ["step-1-8k", "step-1-flash"],
		homeUrl: "https://platform.stepfun.com/",
		apiKeyUrl: "https://platform.stepfun.com/interface-key",
		docsUrl: "https://platform.stepfun.com/docs/overview/concept",
		modelsUrl: "https://platform.stepfun.com/docs/llm/text",
	},
	{
		templateId: "yi",
		name: "零一万物",
		providerType: ProviderType.Custom,
		icon: Globe,
		color: "bg-[#0F766E]",
		defaultEnabled: false,
		defaultApiBase: "https://api.lingyiwanwu.com",
		defaultModels: ["yi-lightning", "yi-vision-v2"],
		homeUrl: "https://platform.lingyiwanwu.com/",
		apiKeyUrl: "https://platform.lingyiwanwu.com/apikeys",
		docsUrl: "https://platform.lingyiwanwu.com/docs",
		modelsUrl: "https://platform.lingyiwanwu.com/docs#%E6%A8%A1%E5%9E%8B",
	},
	{
		templateId: "zai",
		name: "Z.ai",
		providerType: ProviderType.Custom,
		icon: Layers,
		color: "bg-[#111827]",
		defaultEnabled: false,
		defaultApiBase: "https://api.z.ai/api/paas/v4/",
		defaultModels: ["glm-5", "glm-4.7", "glm-4.6", "glm-4.5-flash"],
		homeUrl: "https://z.ai",
		apiKeyUrl: "https://z.ai/manage-apikey/apikey-list",
		docsUrl: "https://docs.z.ai/",
		modelsUrl: "https://docs.z.ai/models",
	},
	{
		templateId: "xirang",
		name: "Xirang",
		providerType: ProviderType.Custom,
		icon: Globe,
		color: "bg-[#0EA5E9]",
		defaultEnabled: false,
		defaultApiBase: "https://wishub-x1.ctyun.cn",
		defaultModels: [],
		homeUrl: "https://www.ctyun.cn",
		apiKeyUrl: "https://huiju.ctyun.cn/service/serviceGroup",
		docsUrl: "https://www.ctyun.cn/products/ctxirang",
		modelsUrl: "https://huiju.ctyun.cn/modelSquare/",
	},
	{
		templateId: "hunyuan",
		name: "腾讯混元",
		providerType: ProviderType.Custom,
		icon: Box,
		color: "bg-[#2563EB]",
		defaultEnabled: false,
		defaultApiBase: "https://api.hunyuan.cloud.tencent.com",
		defaultModels: [
			"hunyuan-pro",
			"hunyuan-standard",
			"hunyuan-vision",
			"hunyuan-code",
		],
		homeUrl: "https://cloud.tencent.com/product/hunyuan",
		apiKeyUrl: "https://console.cloud.tencent.com/hunyuan/api-key",
		docsUrl: "https://cloud.tencent.com/document/product/1729/111007",
		modelsUrl: "https://cloud.tencent.com/document/product/1729/104753",
	},
	{
		templateId: "tencent-cloud-ti",
		name: "Tencent Cloud TI",
		providerType: ProviderType.Custom,
		icon: Box,
		color: "bg-[#1D4ED8]",
		defaultEnabled: false,
		defaultApiBase: "https://api.lkeap.cloud.tencent.com",
		defaultModels: ["deepseek-r1", "deepseek-v3"],
		homeUrl: "https://cloud.tencent.com/product/ti",
		apiKeyUrl: "https://console.cloud.tencent.com/lkeap/api",
		docsUrl: "https://cloud.tencent.com/document/product/1772",
		modelsUrl: "https://console.cloud.tencent.com/tione/v2/aimarket",
	},
	{
		templateId: "baidu-cloud",
		name: "Baidu Cloud",
		providerType: ProviderType.Custom,
		icon: Box,
		color: "bg-[#2563EB]",
		defaultEnabled: false,
		defaultApiBase: "https://qianfan.baidubce.com/v2/",
		defaultModels: [
			"deepseek-r1",
			"deepseek-v3",
			"ernie-4.0-8k-latest",
			"ernie-4.0-turbo-8k-latest",
		],
		homeUrl: "https://cloud.baidu.com/",
		apiKeyUrl: "https://console.bce.baidu.com/iam/#/iam/apikey/list",
		docsUrl: "https://cloud.baidu.com/doc/index.html",
		modelsUrl: "https://cloud.baidu.com/doc/WENXINWORKSHOP/s/Fm2vrveyu",
	},
	{
		templateId: "voyageai",
		name: "VoyageAI",
		providerType: ProviderType.Custom,
		icon: Box,
		color: "bg-[#0F766E]",
		defaultEnabled: false,
		defaultApiBase: "https://api.voyageai.com",
		defaultModels: ["voyage-3-large", "voyage-3", "voyage-code-3", "rerank-2"],
		homeUrl: "https://www.voyageai.com/",
		apiKeyUrl: "https://dashboard.voyageai.com/organization/api-keys",
		docsUrl: "https://docs.voyageai.com/docs",
		modelsUrl: "https://docs.voyageai.com/docs",
	},
	{
		templateId: "qiniu",
		name: "七牛云 AI",
		providerType: ProviderType.Custom,
		icon: Network,
		color: "bg-[#0EA5E9]",
		defaultEnabled: false,
		defaultApiBase: "https://api.qnaigc.com",
		defaultModels: [
			"deepseek-r1",
			"deepseek-v3",
			"qwen2.5-72b-instruct",
			"qwq-32b",
		],
		homeUrl: "https://qiniu.com",
		apiKeyUrl: "https://portal.qiniu.com/ai-inference/api-key",
		docsUrl: "https://developer.qiniu.com/aitokenapi",
		modelsUrl: "https://developer.qiniu.com/aitokenapi/12883/model-list",
	},
	{
		templateId: "longcat",
		name: "LongCat",
		providerType: ProviderType.Custom,
		icon: MessageSquare,
		color: "bg-[#F59E0B]",
		defaultEnabled: false,
		defaultApiBase: "https://api.longcat.chat/openai",
		defaultModels: ["LongCat-Flash-Chat", "LongCat-Flash-Thinking"],
		homeUrl: "https://longcat.chat",
		apiKeyUrl: "https://longcat.chat/platform/api_keys",
		docsUrl: "https://longcat.chat/platform/docs/zh/",
		modelsUrl: "https://longcat.chat/platform/docs/zh/APIDocs.html",
	},
	{
		templateId: "infini",
		name: "Infini AI",
		providerType: ProviderType.Custom,
		icon: Box,
		color: "bg-[#0891B2]",
		defaultEnabled: false,
		defaultApiBase: "https://cloud.infini-ai.com/maas",
		defaultModels: [
			"deepseek-r1",
			"deepseek-v3",
			"qwen2.5-72b-instruct",
			"qwen2.5-coder-32b-instruct",
		],
		homeUrl: "https://cloud.infini-ai.com/",
		apiKeyUrl: "https://cloud.infini-ai.com/iam/secret/key",
		docsUrl:
			"https://docs.infini-ai.com/gen-studio/api/maas.html#/operations/chatCompletions",
		modelsUrl: "https://cloud.infini-ai.com/genstudio/model",
	},
	{
		templateId: "grok",
		name: "xAI Grok",
		providerType: ProviderType.Custom,
		icon: Box,
		color: "bg-[#18181B]",
		defaultEnabled: false,
		defaultApiBase: "https://api.x.ai",
		defaultModels: ["grok-4", "grok-3", "grok-3-fast", "grok-3-mini"],
		homeUrl: "https://x.ai/",
		apiKeyUrl: "https://console.x.ai/",
		docsUrl: "https://docs.x.ai/",
		modelsUrl: "https://docs.x.ai/docs/models",
	},
	{
		templateId: "nvidia",
		name: "NVIDIA NIM",
		providerType: ProviderType.Custom,
		icon: Box,
		color: "bg-[#76B900]",
		defaultEnabled: false,
		defaultApiBase: "https://integrate.api.nvidia.com",
		defaultModels: ["meta/llama-3.1-405b-instruct", "01-ai/yi-large"],
		homeUrl: "https://build.nvidia.com/explore/discover",
		apiKeyUrl: "https://build.nvidia.com/meta/llama-3_1-405b-instruct",
		docsUrl: "https://docs.api.nvidia.com/nim/reference/llm-apis",
		modelsUrl: "https://build.nvidia.com/nim",
	},
	{
		templateId: "jina",
		name: "Jina AI",
		providerType: ProviderType.Custom,
		icon: SearchCode,
		color: "bg-[#7C2D12]",
		defaultEnabled: false,
		defaultApiBase: "https://api.jina.ai",
		defaultModels: [
			"jina-clip-v2",
			"jina-embeddings-v3",
			"jina-embeddings-v2-base-zh",
		],
		homeUrl: "https://jina.ai",
		apiKeyUrl: "https://jina.ai/",
		docsUrl: "https://jina.ai",
		modelsUrl: "https://jina.ai",
	},
	{
		templateId: "ppio",
		name: "PPIO",
		providerType: ProviderType.Custom,
		icon: Gauge,
		color: "bg-[#F97316]",
		defaultEnabled: false,
		defaultApiBase: "https://api.ppinfra.com/v3/openai/",
		defaultModels: [
			"deepseek/deepseek-v3.2",
			"minimax/minimax-m2",
			"qwen/qwen3-235b-a22b-instruct-2507",
		],
		homeUrl: "https://ppio.com",
		apiKeyUrl: "https://ppio.com/settings/key-management",
		docsUrl: "https://docs.ppinfra.com",
		modelsUrl: "https://ppio.com/model-api/product/llm-api",
	},
	{
		templateId: "302ai",
		name: "302.AI",
		providerType: ProviderType.Custom,
		icon: Network,
		color: "bg-[#22C55E]",
		defaultEnabled: false,
		defaultApiBase: "https://api.302.ai",
		defaultModels: [
			"deepseek-chat",
			"deepseek-reasoner",
			"gpt-4.1",
			"claude-sonnet-4-20250514",
		],
		homeUrl: "https://302.ai",
		apiKeyUrl: "https://dash.302.ai/apis/list",
		docsUrl: "https://302ai.apifox.cn/api-147522039",
		modelsUrl: "https://302.ai/pricing/",
	},
	{
		templateId: "dmxapi",
		name: "DMXAPI",
		providerType: ProviderType.Custom,
		icon: Network,
		color: "bg-[#0F172A]",
		defaultEnabled: false,
		defaultApiBase: "https://www.dmxapi.cn",
		defaultModels: [
			"gpt-4o",
			"gpt-4o-mini",
			"DMXAPI-DeepSeek-R1",
			"claude-3-5-sonnet-20241022",
		],
		homeUrl: "https://www.dmxapi.cn",
		apiKeyUrl: "https://www.dmxapi.cn",
		docsUrl: "https://doc.dmxapi.cn/",
		modelsUrl: "https://www.dmxapi.cn/pricing",
	},
	{
		templateId: "tokenflux",
		name: "TokenFlux",
		providerType: ProviderType.Custom,
		icon: SlidersHorizontal,
		color: "bg-[#EC4899]",
		defaultEnabled: false,
		defaultApiBase: "https://api.tokenflux.ai/openai/v1",
		defaultModels: [
			"claude-sonnet-4-6",
			"gpt-5.4",
			"gemini-3.1-pro-preview",
			"gemini-2.5-flash",
		],
		homeUrl: "https://api.tokenflux.ai",
		apiKeyUrl: "https://api.tokenflux.ai/dashboard/api-keys",
		docsUrl: "https://api.tokenflux.ai/docs",
		modelsUrl: "https://api.tokenflux.ai/models",
	},
	{
		templateId: "huggingface",
		name: "Hugging Face",
		providerType: ProviderType.Custom,
		icon: Network,
		color: "bg-[#FFD21E]",
		defaultEnabled: false,
		defaultApiBase: "https://router.huggingface.co/v1/",
		defaultModels: [],
		homeUrl: "https://huggingface.co/",
		apiKeyUrl: "https://huggingface.co/settings/tokens",
		docsUrl: "https://huggingface.co/docs",
		modelsUrl: "https://huggingface.co/models",
	},
	{
		templateId: "poe",
		name: "Poe",
		providerType: ProviderType.Custom,
		icon: MessageSquare,
		color: "bg-[#111827]",
		defaultEnabled: false,
		defaultApiBase: "https://api.poe.com/v1/",
		defaultModels: ["Claude-Sonnet-4.6", "GPT-5.2", "Gemini-3.1-Pro", "Grok-4"],
		homeUrl: "https://poe.com/",
		apiKeyUrl: "https://poe.com/api/keys",
		docsUrl:
			"https://creator.poe.com/docs/external-applications/openai-compatible-api",
		modelsUrl: "https://poe.com/",
	},
	{
		templateId: "mimo",
		name: "Xiaomi MiMo",
		providerType: ProviderType.Custom,
		icon: Box,
		color: "bg-[#2563EB]",
		defaultEnabled: false,
		defaultApiBase: "https://api.xiaomimimo.com",
		defaultModels: [
			"mimo-v2.5",
			"mimo-v2.5-pro",
			"mimo-v2-flash",
			"mimo-v2-omni",
		],
		homeUrl: "https://platform.xiaomimimo.com/",
		apiKeyUrl: "https://platform.xiaomimimo.com/#/console/usage",
		docsUrl: "https://platform.xiaomimimo.com/#/docs/welcome",
		modelsUrl: "https://platform.xiaomimimo.com/",
	},
	// 工作流/Agent
	{
		templateId: "dify",
		name: "Dify",
		providerType: ProviderType.Dify,
		icon: Workflow,
		color: "bg-indigo-600",
		defaultEnabled: false,
		defaultApiBase: "https://api.dify.ai/v1",
		defaultModels: [],
		docsUrl: "https://docs.dify.ai/",
		homeUrl: "https://dify.ai",
	},
	// 自定义
	{
		templateId: "custom",
		name: "自定义 OpenAI 兼容",
		providerType: ProviderType.Custom,
		icon: Plug,
		color: "bg-zinc-500",
		defaultEnabled: false,
		defaultModels: [],
	},
];

// 核心服务商 - 这些会在初始化时自动创建
// 注意：新增的服务商默认不会自动创建，需要用户手动添加
// 后端会自动创建这21个核心服务商模板
export const CORE_PROVIDER_IDS = [
	"openai",
	"anthropic",
	"gemini",
	"deepseek",
	"zhipu",
	"moonshot",
	"cherryin",
	"ovms",
	"ocoolai",
	"alayanew",
	"aionly",
	"burncloud",
	"cephalon",
	"lanyun",
	"ph8",
	"sophnet",
	"dashscope",
	"modelscope",
	"doubao",
	"minimax",
	"minimax-global",
	"baichuan",
	"stepfun",
	"yi",
	"zai",
	"xirang",
	"hunyuan",
	"tencent-cloud-ti",
	"baidu-cloud",
	"voyageai",
	"qiniu",
	"longcat",
	"infini",
	"grok",
	"nvidia",
	"jina",
	"ppio",
	"302ai",
	"dmxapi",
	"tokenflux",
	"huggingface",
	"poe",
	"mimo",
	"silicon",
	"aihubmix",
	"openrouter",
	"together",
	"groq",
	"fireworks",
	"mistral",
	"ollama",
	"lmstudio",
	"newapi",
	"github",
	"perplexity",
	"cerebras",
	"hyperbolic",
	"dify",
];

// 可选服务商模板 - 用户可以手动添加（所有非核心的模板）
export const OPTIONAL_TEMPLATES: ProviderTemplate[] = PROVIDER_TEMPLATES.filter(
	(t) => !CORE_PROVIDER_IDS.includes(t.templateId),
);

export interface Provider {
	id: string;
	templateId?: string;
	providerType: ProviderType;
	name: string;
	icon?: LucideIcon;
	color: string;
	isEnabled: boolean;
	apiKey?: string;
	apiBase?: string;
	models: string[];
	metadata?: Record<string, any>;
}

export const DEFAULT_PROVIDERS: Provider[] = PROVIDER_TEMPLATES.map(
	(template) => ({
		id: template.templateId,
		templateId: template.templateId,
		providerType: template.providerType,
		name: template.name,
		icon: template.icon,
		color: template.color,
		isEnabled: template.defaultEnabled,
		apiBase: template.defaultApiBase,
		models: template.defaultModels,
		metadata: { templateId: template.templateId },
	}),
);
